# This module is called userId.py
# This program will create a Conn user name

def userId():

    #print some welcome message
    print ("Welcome to Connecticut College!")
    print ("I will now generate your Conn College network user name.")

    #ask name
    wholeName = input("Please enter your first and last names separated by spaces --> ")

    #split name into first and last
    names = wholeName.split()
    
    # assign firstName and lastName variable
    firstName = names[0]
    lastName = names[1]
    
    #new IDs are generated by taking first initial of first name, then
    #last name (i.e. James Lee => jlee)
    username = firstName[0] + lastName
    
    #output the username (i.e. Yor username is xxxxxx)
    print("Your username is", username.lower())
    
    #email: firstName.lastName (i.e. James Lee => james.lee@conncoll.edu) 
    email = firstName.lower()+"."+lastName.lower()+"@conncoll.edu"
    
    #output email address (i.e. Your email address is xxxx.yyyy@conncoll.edu)
    print("Your email address is", email)
    
userId()
