# This module is called userId.py
# This program will create a Conn user name

def userId():

    #print some welcome message
    print ("Welcome to Connecticut College!")
    print ("I will now generate your Conn College network user name.")

    #ask name
    wholeName = input("Please enter your first, middle, and last names separated by spaces --> ")

    #split name into first, middle, and last
    names = wholeName.split()
    
    # assign firstName, middleName, and lastName variables
    firstName = names[0]
    middleName = names[1]
    lastName = names[2]
    
    #new IDs are generated by taking first initial of first name and middle name, then
    #the first three characters of the last name (i.e. Russell Harry Kosovsky => rhkos)
    username = firstName[0] + middleName[0] + lastName[0:3]
    
    #output the username (i.e. Yor username is xxxxxx)
    print("Your username is", username.lower())
    
    #email: firstName.lastName (i.e. James Lee => james.lee@conncoll.edu) 
    email = firstName.lower()+"."+lastName.lower()+"@conncoll.edu"
    
    #output email address (i.e. Your email address is xxxx.yyyy@conncoll.edu)
    print("Your email address is", email)
    
userId()
